src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="text")
     */
    private $note;

    /**
     * @ORM\Column(type="date")
     */
    private $added_on;

    /**
     * @Assert\File(maxSize = "5M", groups = {"create"})
     * @ORM\Column(type="string", length=255)
     */
    private $imageFile;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        if(empty($roles)) {
            $roles[] = 'ROLE_EDITOR';
        }

        return array_unique($roles);
    }
    
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(string $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getAddedOn(): ?\DateTimeInterface
    {
        return $this->added_on;
    }

    public function setAddedOn(\DateTimeInterface $added_on): self
    {
        $this->added_on = $added_on;

        return $this;
    }

    public function getImageFile(): ?string
    {
        return $this->imageFile;
    }

    public function setImageFile(string $category_picture): self
    {
        $this->imageFile = $category_picture;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

   
  
}

src/Controller/AccountsController.php
<?php

namespace App\Controller;

use App\Entity\Accounts;
use App\Form\AccountsType;
use App\Repository\AccountsRepository;
use Gedmo\Sluggable\Util\Urlizer;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/accounts")
 */
class AccountsController extends AbstractController
{
    /**
     * @Route("/", name="app_accounts_index", methods={"GET"}, options={"expose"=true})
     */
    public function index(AccountsRepository $accountsRepository, Request $request,  PaginatorInterface $paginator): Response
    {
        $data = $accountsRepository->findAll();
        // Paginate the data
        $pagination = $paginator->paginate(
            $data, // Query builder, collection, or array of data
            $request->query->getInt('page', 1), // Current page number
            5 // Number of items to display per page
        );
        return $this->render('accounts/index.html.twig', [
            'pagination' => $pagination
        ]);
    }

    /**
     * @Route("/new", name="app_accounts_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AccountsRepository $accountsRepository): Response
    {
        $account = new Accounts();
        $form = $this->createForm(AccountsType::class, $account);
        $form->handleRequest($request);

        if ($request->isMethod('POST')) {
            if ($form->isSubmitted() && $form->isValid()) {
                $file = $form->get('imageFile')->getData();
                if ($file) {
                    $fileName = md5(uniqid()) . '.' . $file->guessExtension();
                    try {
                        $file->move(
                            $this->getParameter('images_user_directory'),
                            $fileName
                        );
                    } catch (FileException $e) {
                        $e->getMessage();
                    }

                    $account->setImageFile($fileName);
                }
                $accountsRepository->add($account, true);
                $this->addFlash('success', 'Your form is submitted successfully.');
                return $this->redirectToRoute('app_accounts_index');
            } else {
                $this->addFlash('danger', 'Submit failed.');
            }
        }
        return $this->renderForm('accounts/new.html.twig', [
            'account' => $account,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_accounts_show", methods={"GET"})
     */
    public function show(Accounts $account): Response
    {
        return $this->render('accounts/show.html.twig', [
                'account' => $account,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_accounts_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Accounts $account, AccountsRepository $accountsRepository): Response
    {
        $form = $this->createForm(AccountsType::class, $account);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            if ($form->isValid()) {
                $uploadedFile = $form['imageFile']->getData();
                if ($uploadedFile) {
                    $destination = $this->getParameter('images_user_directory');
                    $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
                    $newFilename = Urlizer::urlize($originalFilename).'-'.uniqid().'.'.$uploadedFile->guessExtension();
                    $uploadedFile->move(
                        $destination,
                        $newFilename
                    );

                    $account->setImageFile($newFilename);
                }

                $accountsRepository->add($account, true);
                $this->addFlash('success', 'Your form is edited successfully.');
                return $this->redirectToRoute('app_accounts_index', [], Response::HTTP_SEE_OTHER);
            } else {
                $this->addFlash('danger', 'Submit failed.');

            }
        }

        return $this->renderForm('accounts/edit.html.twig', [
            'account' => $account,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/delete/{id}", name="app_accounts_delete", methods={"POST"})
     */
    public function delete(Request $request, Accounts $account, AccountsRepository $accountsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$account->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($account);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_accounts_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/search", name="search", methods={"GET"}, options={"expose"=true})
     */
    public function search(Request $request, AccountsRepository $accountsRepository)
    {
        $query = $request->query->get('query');
        $accounts = $accountsRepository->findByString($query);
        if(!$accounts) {
            $result['posts']['error'] = "Post Not found :( ";
        } else {
            $result['posts'] = $this->getRealEntities($accounts);
        }
            return new Response(json_encode($result));
    }

    public function getRealEntities($posts){
        foreach ($posts as $posts){
            $realEntities[$posts->getId()] = [
                $posts->getEmail(),
                $posts->getName(),
                $posts->getRoles(),
                $posts->getAddedOn()
            ];

        }
        return $realEntities;
    }
}

templates/accounts/_form.html.twig
{% block content %}
    <div class="row">
        <div class="card">
            {{ form_start(form,{'attr':{'novalidate':'novalidate'}} ) }}


            <div class="mb-3">
                <label class="form-label" for="article-title-input">Email</label>
                {{ form_widget(form.email, {'attr': {'class': 'form-control', 'placeholder': 'Enter your email'}}) }}
                {% if form_errors(form.email)is not empty %}
                    <div class="alert alert-danger">
                        {{ form_errors(form.email) }}
                    </div>
                {% endif %}
            </div>

            <div class="mb-3">
                <label class="form-label" for="article-title-input">Roles</label>
                {{ form_widget(form.roles, {'attr': {'class': 'form-control'}}) }}
                {% if form_errors(form.roles)is not empty %}
                    <div class="alert alert-danger">
                        {{ form_errors(form.roles) }}
                    </div>
                {% endif %}
            </div>


            <div class="mb-3">
                <label class="form-label" for="url-input">Password</label>
                {{ form_widget(form.password, {'attr': {'class': 'form-control'}}) }}
                {% if form_errors(form.password)is not empty %}
                    <div class="alert alert-danger">
                        {{ form_errors(form.password) }}
                    </div>
                {% endif %}

            </div>


            <div class="mb-3">
                <label class="form-label" for="body-input">Name</label>
                {{ form_widget(form.name, {'attr': {'class': 'form-control', 'placeholder': 'Enter your name'}}) }}
                {% if form_errors(form.name)is not empty %}
                    <div class="alert alert-danger">
                        {{ form_errors(form.name) }}
                    </div>
                {% endif %}
            </div>

            <div class="mb-3">
                <label class="form-label" for="body-input">First Name</label>
                {{ form_widget(form.first_name, {'attr': {'class': 'form-control'}}) }}
                {% if form_errors(form.first_name)is not empty %}
                    <div class="alert alert-danger">
                        {{ form_errors(form.first_name) }}
                    </div>
                {% endif %}
            </div>

            <div class="mb-3">
                <label class="form-label" for="body-input">Last name</label>
                {{ form_widget(form.last_name, {'attr': {'class': 'form-control'}}) }}
                {% if form_errors(form.last_name)is not empty %}
                    <div class="alert alert-danger">
                        {{ form_errors(form.last_name) }}
                    </div>
                {% endif %}
            </div>

            <div class="mb-3">
                <label class="form-label" for="body-input">Note</label>
                {{ form_widget(form.note, {'attr': {'class': 'form-control'}}) }}
                {% if form_errors(form.note)is not empty %}
                    <div class="alert alert-danger">
                        {{ form_errors(form.note) }}
                    </div>
                {% endif %}
            </div>

            <div class="mb-3">
                <label class="form-label" for="body-input">Added on</label>
                {{ form_widget(form.added_on, {'attr': {'class': 'form-control'}}) }}
                {% if form_errors(form.added_on)is not empty %}
                    <div class="alert alert-danger">
                        {{ form_errors(form.added_on) }}
                    </div>
                {% endif %}
            </div>

            <div class="mb-3">
                <label class="form-label" for="body-input">Piéce jointe</label>
                {{ form_widget(form.imageFile, {'attr': {'class': 'form-control'}}) }}
                {% if form_errors(form.imageFile)is not empty %}
                    <div class="alert alert-danger">
                        {{ form_errors(form.imageFile) }}
                    </div>
                {% endif %}
            </div>

            {{ form_widget(form) }}
            <button type="submit" class="btn btn-success">{{ button_label|default('Save') }}</button>

            {{ form_end(form) }}

        </div>
    </div>

{% endblock %}

templates/accounts/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Accounts{% endblock %}

{% block content %}
    <h1>Edit Accounts</h1>

    {{ include('accounts/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_accounts_index') }}">back to list</a>

{% endblock %}

templates/accounts/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accounts index{% endblock %}
{% block content %}
    <div class="row">
                        <div class="col-12">
                            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                                <h4 class="mb-sm-0">Listing Accounts</h4>

                                <div class="page-title-right">
                                    <ol class="breadcrumb m-0">
                                        <li class="breadcrumb-item"><a href="javascript: void(0);">Accounts</a></li>
                                        <li class="breadcrumb-item active">Listing Accounts</li>
                                    </ol>
                                </div>

                            </div>
                        </div>
                    </div>
                
<div class="card">
                <div class="card-body">
                            <div class="row g-2">
                                <div class="col-lg-auto">
                                    <div class="hstack gap-2">
                                           <a href="{{ path('app_accounts_new') }}"><button type="button" class="btn btn-primary waves-effect waves-ligh" ><i class="ri-add-fill me-1 align-bottom"></i>Add Accounts</button></a>
                                    </div>
                                </div>
                               <div class="col-xxl-6 col-sm-9">
                                                <div class="search-box">
                                                    <form>
                                                        <input type="text" id="search-input">
                                                    </form>
                                                    <i class="ri-search-line search-icon"></i>
                                                </div>
                                            </div>
                                          
                                    <div class="col-auto order-2 order-sm-1 ms-auto">
                                    <div class="hstack gap-2">
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                            <a href="{{ path('app_accounts_index') }}"><button class="btn btn-icon fw-semibold btn-soft-danger"><i class="ri-arrow-go-back-line"></i></button></a>
                                            <a href="{{ path('app_accounts_new') }}"><button class="btn btn-icon fw-semibold btn-soft-success"><i class="ri-arrow-go-forward-line"></i></button></a>
                                        </div>
                                    </div>
                                </div>   
                          </div>
                  </div>
           </div>

<div class="row">
<div class="col-xl-12 grid-margin stretch-card  ">
    <div class="card">
         <div class="card-body">
             <div class="table-responsive">
    <table id="t" class="table align-middle table-nowrap table-striped-columns mb-0">
        <thead class="table-light" >
            <tr> 
                <th scope="col" style="width: 46px;">
                            <div class="form-check">
                                <div class="form-check">
                                       <input class="form-check-input" type="checkbox" value="" id="cardtableCheck01">
                                       <label class="form-check-label" for="cardtableCheck01"></label>
                                </div>
                          </div>

                <th>{{ knp_pagination_sortable(pagination, 'Id', 'id') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Name', 'name') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Email', 'email') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Roles', 'roles') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Added On', 'added_on') }}</th>
                <th scope="col" style="width: 150px;" >Actions</th>
                 </th>                           
            </tr>
        </thead>
        <tbody id="all">
        {% for account in pagination %}
            <tr>  
                <td>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="cardtableCheck01">
                             <label class="form-check-label" for="cardtableCheck01"></label>
                        </div>
                </td>
                <td>{{ account.id }}</td>
                <td>{{ account.name }}</td>
                <td>{{ account.email }}</td>
                <td>{{ account.roles ? account.roles|json_encode : '' }}</td>
                <td>{{ account.addedOn ? account.addedOn|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_accounts_edit', {'id': account.id}) }}"><button class="btn btn-outline-success btn-border"><i class="ri-pencil-fill align-bottom me-2 text-muted"></i></button></a>
                        <a><button class="btn btn-soft-danger btn-border" data-bs-toggle="modal" data-bs-target="#topmodal"><i class="ri-delete-bin-fill align-bottom me-2 text-muted"></i></button>
                            <div id="topmodal" class="modal fade" tabindex="-1" style="display: none;" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-body text-center p-5">
                                            <lord-icon src="https://cdn.lordicon.com/pithnlch.json" trigger="loop" colors="primary:#121331,secondary:#08a88a" style="width:120px;height:120px">
                                            </lord-icon>
                                            <div class="mt-4">
                                                <h3 class="mb-3">Information Message</h3>
                                                <p class="text-muted mb-4">You are deleting this accounts.This action is irreversible.Are you sure?</p>
                                                <div class="hstack gap-2 justify-content-center">
                                                        <a href="javascript:void(0);" class="btn btn-link link-success fw-medium" data-bs-dismiss="modal"><i class="ri-close-line me-1 align-middle"></i> Cancel</a>
                                                    <form method="post" x²>
                                                        <button class="btn btn-success"><input type="hidden" name="_token" value="{{ csrf_token('delete' ~ account.id) }}">Validate</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div><!-- /.modal-content -->
                                </div><!-- /.modal-dialog -->
                            </div>
                        </a>
                        <a href="{{ path('app_accounts_show', {'id': account.id}) }}"><button class="btn btn-outline-secondary btn-border"> <i class="ri-eye-fill align-bottom me-2 text-muted"></i></button></a>

                </td>

            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>

    </table>
                 <div class="navigation text-center">
                     {% if pagination.getTotalItemCount  > 0 %}
                         {{ knp_pagination_render(pagination) }}
                     {% endif %}
                 </div>

             </div>

          </div>

      </div>
    </div>
</div>


    
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>
        $(document).ready(function() {
            var searchInput = $('#search-input');
            var searchResults = $('#all');
            searchInput.on('keyup', function() {
                var query = searchInput.val();
                if (query.length > 0) {
                    $.ajax({
                        url: '/search/',
                        type: 'GET',
                        data: {
                            'query': query,
                        },
                        success: function(response) {
                            var tableBody = $('#t tbody');
                            tableBody.empty(); // clear any existing rows

                            $.each(JSON.parse(response), function(key, arr) {
                                $.each(arr, function(id, value) {
                                    if (key === 'posts') {
                                        if (id !== 'error') {
                                            console.log(value[3].date);
                                            $('#all').append('<tr>' +
                                                '<td><input class="form-check-input" type="checkbox" value="" id="cardtableCheck01"></td>' +
                                                '<td>'+id+'</td>' +
                                                '<td>'+value[1]+'</td>' +
                                                '<td>'+value[0]+'</td>' +
                                                '<td>'+value[2]+'</td>' +
                                                '<td>'+value[3].date.split(' ')[0]+'</td>' +
                                                '<td>' +
                                                '<a href="' +id + '/edit"><button class="btn btn-outline-success btn-border"><i class="ri-pencil-fill align-bottom me-2 text-muted"></i></button></a>' +
                                                '<a href="/accounts/' +id + '"><button class="btn btn-soft-danger btn-border" data-bs-toggle="modal" data-bs-target="#topmodal"><i class="ri-delete-bin-fill align-bottom me-2 text-muted"></i></button></a>' +
                                                '<a href="/accounts/' +id + '"><button class="btn btn-outline-secondary btn-border"> <i class="ri-eye-fill align-bottom me-2 text-muted"></i></button></a>' +
                                                '</td>' +
                                                '</tr>');
                                        }
                                    }
                                });
                            });
                        },
                        error: function(jqXHR, textStatus, errorThrown) {
                            console.log(textStatus + ': ' + errorThrown);
                        }
                    });
                } else {
                    searchResults.empty();
                }
            });
        });
    </script>

    <script>
        $(document).ready(function() {
            // When the user clicks on the delete button
            $(".delete-btn").on("click", function() {
                // Get the ID of the item to delete
                var itemId = $(this).data("id");

                // Set the action of the delete form to the URL for deleting the item
                $("#delete-form").attr("action", "/items/" + itemId);

                // Show the modal
                $("#topmodal").modal("show");
            });

            // When the user confirms the deletion
            $("#delete-form").on("submit", function() {
                // Submit the form
                $(this).submit();
            });
        });
    </script>

{% endblock %}

templates/accounts/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accounts{% endblock %}

{% block content %}
    <h1>Accounts</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ account.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ account.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ account.roles ? account.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ account.password }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ account.name }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ account.firstName }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ account.lastName }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ account.note }}</td>
            </tr>
            <tr>
                <th>Added_on</th>
                <td>{{ account.addedOn ? account.addedOn|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_accounts_index') }}">back to list</a>

    <a href="{{ path('app_accounts_edit', {'id': account.id}) }}">edit</a>

    {{ include('accounts/_delete_form.html.twig') }}
{% endblock %}